

services:
  dev-agent:
    dns:
      - 172.31.250.3
    depends_on:
      - dns

  dns:
    image: andyshinn/dnsmasq:latest
    container_name: devkit_dns
    command: ["-k", "--conf-file=/etc/dnsmasq.d/dnsmasq.conf"]
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.d/dnsmasq.conf:ro
    networks:
      dev-internal:
        ipv4_address: 172.31.250.3
      dev-egress:
        aliases: [dns]

networks:
  dev-internal:
    ipam:
      driver: default
      config:
        - subnet: 172.31.250.0/24
  dev-egress:
    driver: bridge
